CFG_DEST: config.yaml
CUDNN:
  BENCHMARK: true
DATA_LOADER:
  DATA_DIR: /data/zhangxuesong/ABAWdataset/
  EMO_INDEX: -1
  EXPR_MLB: false
  IMG_SIZE: 112
  NUM_WORKERS: 8
  PIN_MEMORY: false
  SAMPLING_METHOD: sequentially
  SEQ_LEN: 64
DATA_NAME: eev
DESC: ''
DOWNLOAD_CACHE: /tmp/pycls-download-cache
FAST_DEV_RUN: 0
GRU:
  BIDIRECTIONAL: false
  DROPOUT: 0.0
  HIDDEN_SIZE: 256
  NUM_LAYERS: 2
LOGGER: TensorBoard
LOG_DEST: stdout
LOG_PERIOD: 10
LSTM:
  BIDIREC: false
  DROPOUT: 0.0
  HIDDEN_SIZE: 64
  NUM_LAYERS: 4
MODEL:
  BACKBONE: regnet-1.6gf
  BACKBONE_FREEZE:
  - block4
  - block3
  - block2
  BACKBONE_PRETRAINED: ''
  FC_HIDDEN: 32
  FEATURES:
  - effb0
  FREEZE_BATCHNORM: true
  LOSS_FUN: mse
  NUM_CLASSES: 15
  TEMPORAL_TYPE: tcn
  USE_POSITION: true
MODEL_NAME: only_trans
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.001
  DAMPENING: 0.0
  EMA_ALPHA: 1.0e-05
  EMA_UPDATE_PERIOD: 32
  FOCAL_ALPHA: 0.9
  FOCAL_GAMMA: 2.0
  LR_MULT: 0.1
  LR_POLICY: reducelrMetric
  MAX_EPOCH: 30
  MIN_LR: 0.0
  MOMENTUM: 0.9
  NAME: adamw
  NESTEROV: true
  STEPS: []
  TUNE_LR: false
  USE_SWA: false
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 5.0e-05
OUT_DIR: /home/xuesongzhang/ABAW/PRLbase/beifen/334/tmptest/
RNG_SEED: 1
TASK: EXPR
TCN:
  DILATIONS: 4
  DROPOUT: 0.0
  K_SIZE: 3
  NORM: true
  NUM_CHANNELS: 512
  NUM_HEAD: 1
  NUM_STACK: 2
TEST:
  BATCH_SIZE: 16
  DATASET: ''
  SPLIT: val
  WEIGHTS: ''
TEST_ONLY: /home/xuesongzhang/ABAW/bestmodel/2023-03-05_17-02-16-0.346/checkpoints/epoch=19-step=11619.ckpt
TRAIN:
  ACCUM_GRAD_BATCHES: 1
  AUTO_RESUME: true
  BATCH_SIZE: 16
  DATASET: ''
  DROP_PERC: 0.3
  LABEL_SMOOTHING: 0.1
  LIMIT_TRAIN_BATCHES: 1.0
  LOSS_WEIGHTS: false
  MIXED_PRECISION: true
  SPLIT: train
  WEIGHTS: ''
TRANF:
  DIM_FC: 512
  DROPOUT: 0.3
  NHEAD: 4
  NUM_ENC_DEC: 3
VERBOSE: true
